Moved the metadata from setup.py into setup.cfg
erikrose/parsimonious pull request #174
Opened 2020-11-16 09:30 UTC by KOLANICH

>(Soon to be) the fastest pure-Python PEG parser 

In fact the fastest I have benchmarked.

2021-01-12 17:44 UTC, KOLANICH commented
@erikrose

2021-01-19 16:26 UTC, evanh commented
Can you clarify why you made this change?

2021-01-19 17:46 UTC, KOLANICH commented
For better security when building packages somewhen in future.

2022-09-07 17:45 UTC, lucaswiman requested changes
One small change. I was able to do an editable install (`pip install -e .`) and generate a sensible looking dist file. After some googling, I haven't found a straight answer about whether setup.cfg is preferred or pyproject.toml is. It seems like both are maintained?

Since you're suggesting this change, could you comment on why .toml is preferred over .cfg?

2022-09-07 17:45 UTC, lucaswiman commented on pyproject.toml
> +requires = ["setuptools>=61.2.0", "wheel", "setuptools_scm[toml]>=3.4.3"]
Does this mean the end user needs to have these tools installed or just the person who builds the dist file and wheel?

2022-09-07 18:26 UTC, KOLANICH commented
1. about whether setup.cfg is preferred or pyproject.toml

`setup.cfg` is deprecated since PEP 621 being implemented in `setuptools`. 

2. >Does this mean the end user needs to have these tools installed or just the person who builds the dist file and wheel?

Only for the one building packages. `pyproject.toml` is used when python packages are built from source. Wheels uave own metadata.

2022-09-07 19:16 UTC, lucaswiman approved these changes
OK, LGTM. Thanks for this!

2022-09-07 19:16 UTC, merged